name: Start New Release

on:
  workflow_dispatch:
    inputs:
      version_fragment:
        description: 'The versions fragment you want to increment. Possible options are [ major | feature | bug | alpha | beta | rc ]'
        default: 'feature'
        required: true

jobs:
  start-new-release:
    name: Start New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch to release
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@entrnce.com"

      - name: Read version and remove SNAPSHOT
        id: read_version
        run: |
          version=$(sh ./gradlew --build-cache properties | grep "^version:" | cut -d" " -f2 | sed 's/-SNAPSHOT//g')
          echo "::set-output name=version::$version"

      - name: Create Release branch
        run: |
          git checkout -b release/${{ steps.read_version.outputs.version }}

      - name: Remove occurences of SNAPSHOT from build gradle
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: "-SNAPSHOT"
          replace: ""
          include: "build.gradle"

      - name: Add commit to release branch
        run: |
          git add build.gradle
          git commit --message "Bump version for release ${{ steps.read_version.outputs.version }}."


      - name: Checkout develop
        run: |
          git checkout develop

      - name: Bump version for next development iteration
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.read_version.outputs.version }}
          version-fragment: ${{ github.event.inputs.version_fragment }}
      - name: Update applicationVersion to next development SNAPSHOT version
        uses: jacobtomlinson/gha-find-replace@0.1.2
        id: change_next_development_version
        with:
          find: "([ ]*)applicationVersion([ ]*)=([ ]*)[^\r\n]*"
          replace: "${1}applicationVersion${2}=${3}'${{ steps.bump_version.outputs.next-version }}-SNAPSHOT'"
          include: "build.gradle"
      - name: Verify the applicationVersion has changed in a single file
        run: |
          [[ 1 == ${{ steps.change_next_development_version.outputs.modifiedFiles }} ]]

      - name: Add, commit and push to develop
        run: |
          git add build.gradle
          git commit --message "Next development iteration for version ${{ steps.bump_version.outputs.next-version }}-SNAPSHOT."

      - name: Push changes to Git
        run: |
          git push origin release/${{ steps.read_version.outputs.version }}
          git push origin develop
